// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYaa5Xk8yG2MrgpzNXwz0R9-B-di7xF0w',
    appId: '1:1058989108526:web:897b3d7852dff019f8debf',
    messagingSenderId: '1058989108526',
    projectId: 'food-donation-508f1',
    authDomain: 'food-donation-508f1.firebaseapp.com',
    storageBucket: 'food-donation-508f1.appspot.com',
    measurementId: 'G-K4TQR0J42J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiO0CR3WcTyd1Oizc-Gu2HB2moLyAaZzY',
    appId: '1:1058989108526:android:861498abaf4a250cf8debf',
    messagingSenderId: '1058989108526',
    projectId: 'food-donation-508f1',
    storageBucket: 'food-donation-508f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHwFhlQGawLAgQhSUtjxwzEwrnCFM5Mg',
    appId: '1:1058989108526:ios:ad3cec7f959626fef8debf',
    messagingSenderId: '1058989108526',
    projectId: 'food-donation-508f1',
    storageBucket: 'food-donation-508f1.appspot.com',
    iosClientId: '1058989108526-8dsknmpaamhsb14i6cbeh1381lblsevu.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHwFhlQGawLAgQhSUtjxwzEwrnCFM5Mg',
    appId: '1:1058989108526:ios:30e7b8f4fcccec62f8debf',
    messagingSenderId: '1058989108526',
    projectId: 'food-donation-508f1',
    storageBucket: 'food-donation-508f1.appspot.com',
    iosClientId: '1058989108526-nen61n0lbl1thkv0veuqvcjo196cjqno.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
